#!/usr/bin/env node
// Binds code to an installation at build time. For every config/<installation>/ with a profile.json it writes
//   .wrangler/generated/<installation>/installation.ts             static imports of profile + policies, assembled fail-closed
//   .wrangler/generated/<installation>/<deployable>/wrangler.jsonc  deploy/cloudflare/<deployable>/wrangler.jsonc (code, identical
//                                                                   for every installation) + alias "apf:installation" -> that module
//                                                                   + vars.INSTALLATION + config/<installation>/farm.json overlay (routes, vars)
// A base config cannot be built alone: code + installation = deployable. Output is git-ignored; deploy and dry-run from there.
// Usage: node scripts/farm-config.mjs [installation ...]   (default: every installation with a profile)

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parseJsonc } from "./jsonc.mjs";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const farmDir = join(repoRoot, "deploy", "cloudflare");
const configDir = join(repoRoot, "config");
export const ALIAS = "apf:installation";

const posix = (p) => p.split("\\").join("/");
const relFrom = (fromDir, target) => {
  const r = posix(relative(fromDir, target));
  return r.startsWith(".") ? r : `./${r}`;
};

/** Objects merge key by key, arrays and scalars from the overlay replace the base value. */
export function merge(base, overlay) {
  if (Array.isArray(base) || Array.isArray(overlay) || typeof base !== "object" || typeof overlay !== "object" || base === null || overlay === null) return overlay;
  const out = { ...base };
  for (const [k, v] of Object.entries(overlay)) out[k] = k in out ? merge(out[k], v) : v;
  return out;
}

export function installations() {
  if (!existsSync(configDir)) return [];
  return readdirSync(configDir)
    .filter((d) => statSync(join(configDir, d)).isDirectory() && existsSync(join(configDir, d, "profile.json")))
    .sort();
}

export function deployables() {
  return readdirSync(farmDir)
    .filter((d) => statSync(join(farmDir, d)).isDirectory() && existsSync(join(farmDir, d, "wrangler.jsonc")))
    .sort();
}

/** The only file that names config/<installation>/ files. Workers import it as apf:installation; the alias picks the installation. */
export function generateInstallationModule(installation, root = repoRoot) {
  const dir = join(root, "config", installation);
  if (!existsSync(join(dir, "profile.json"))) throw new Error(`config/${installation}/profile.json does not exist`);
  const outDir = join(root, ".wrangler", "generated", installation);
  mkdirSync(outDir, { recursive: true });
  const policyDir = join(dir, "policy");
  const policies = existsSync(policyDir) ? readdirSync(policyDir).filter((f) => f.endsWith(".policy.json")).sort() : [];
  const lines = [
    `// Generated by scripts/farm-config.mjs from config/${installation}. Do not edit; regenerate.`,
    `// Bound at build time through the wrangler alias "${ALIAS}". Assembly runs at import: a broken profile keeps the Worker from starting.`,
    `import { assembleInstallation, type Installation } from "${relFrom(outDir, join(root, "src", "installation.js"))}";`,
    `import type { Policy } from "${relFrom(outDir, join(root, "src", "platform", "policy.js"))}";`,
    `import profile from "${relFrom(outDir, join(dir, "profile.json"))}" with { type: "json" };`,
    ...policies.map((f, i) => `import policy${i} from "${relFrom(outDir, join(policyDir, f))}" with { type: "json" };`),
    "",
    `export const INSTALLATION = ${JSON.stringify(installation)};`,
    `export const installation: Installation = assembleInstallation(profile, [${policies.map((_, i) => `policy${i}`).join(", ")}] as Policy[]);`,
    "",
  ];
  const file = join(outDir, "installation.ts");
  writeFileSync(file, lines.join("\n"));
  return file;
}

/** Writes the installation module and one config per deployable; returns the config paths. */
export function generateFarmConfigs(installation, root = repoRoot) {
  const farmFile = join(root, "config", installation, "farm.json");
  const overlay = existsSync(farmFile) ? JSON.parse(readFileSync(farmFile, "utf8")) : {};
  const known = deployables();
  for (const name of Object.keys(overlay)) {
    if (name.startsWith("$")) continue;
    if (!known.includes(name)) throw new Error(`config/${installation}/farm.json names ${name}, but deploy/cloudflare/${name}/wrangler.jsonc does not exist`);
  }
  const moduleFile = generateInstallationModule(installation, root);
  const written = [];
  for (const d of known) {
    const baseFile = join(farmDir, d, "wrangler.jsonc");
    const base = parseJsonc(readFileSync(baseFile, "utf8"));
    const targetDir = join(root, ".wrangler", "generated", installation, d);
    mkdirSync(targetDir, { recursive: true });
    // $signingPublicKeys is metadata, not a per-deployable overlay (skipped above): any deployable whose base config
    // already declares SIGNING_PUBLIC_KEYS gets it verbatim, so the key lives in exactly one place (farm.json), never
    // copy-pasted per deployable. A deployable that does not declare the var (it never verifies a signature) is untouched.
    const signingPublicKeys =
      base.vars && "SIGNING_PUBLIC_KEYS" in base.vars && overlay.$signingPublicKeys
        ? JSON.stringify(Object.fromEntries(Object.entries(overlay.$signingPublicKeys).filter(([k]) => !k.startsWith("$"))))
        : undefined;
    const bound = {
      ...base,
      vars: { ...(base.vars ?? {}), INSTALLATION: installation, ...(signingPublicKeys ? { SIGNING_PUBLIC_KEYS: signingPublicKeys } : {}) },
      alias: { ...(base.alias ?? {}), [ALIAS]: relFrom(targetDir, moduleFile) },
    };
    const merged = merge(bound, overlay[d] ?? {});
    // Paths in a wrangler config are relative to the config file; the generated file lives elsewhere than the source.
    delete merged.$schema;
    if (typeof base.main === "string") merged.main = relFrom(targetDir, join(dirname(baseFile), base.main));
    const target = join(targetDir, "wrangler.jsonc");
    writeFileSync(target, `${JSON.stringify(merged, null, 2)}\n`);
    written.push(target);
  }
  return written;
}

const invokedDirectly = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) {
  const names = process.argv.length > 2 ? process.argv.slice(2) : installations();
  if (!names.length) console.log("farm-config: no config/*/profile.json, nothing to generate");
  for (const name of names) {
    for (const file of generateFarmConfigs(name)) console.log(`generated ${posix(relative(repoRoot, file))}`);
  }
}
